service: nodebr-meetup-serverless-api-demo

provider:
  name: aws
  runtime: nodejs6.10

functions:
  graphql:
    handler: lambda.graphql
    environment:
      TWITTER_CONSUMER_KEY: some-value
      TWITTER_CONSUMER_SECRET: some-value
      TWITTER_ACCESS_TOKEN: some-value
      TWITTER_ACCESS_TOKEN_SECRET: some-value
    events:
     - http:
        path: graphql
        method: post
     - http:
        path: graphql
        method: get

  graphiql:
    handler: lambda.graphiql
    environment:
      GRAPHQL_URL: some-url
    events:
     - http:
        path: graphiql
        method: get
